apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - image: dsyer/demo
        name: demo
        env:
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        - name: JAVA_OPTS
          value: -Dspring.main.lazy-initialization=true -noverify -XX:TieredStopAtLevel=1
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
